# TODO: Move configuration to nix 
set -ga terminal-overrides ",xterm-256color:Tc"

# tmux make vim `Esc` slow, this fix it
set -sg escape-time 50


set -g status-left-length 30

# Plugins
# --- extrakto
set -g @extrakto_popup_size "80%,50%"

# --- sesh
bind-key "S" display-popup -E -w 40% "sesh connect \"$( \
 sesh list -i | gum filter --limit 1 --no-sort --fuzzy --placeholder 'Pick a sesh' --height 50 --prompt='⚡'\
)\""
