#!/usr/bin/env bash
# changeBrightness

# Arbitrary but unique message tag
msgTag="myBrightness"

# 1 second short notification
timeout=1000

brightnessctl "$@" > /dev/null
brightness=$(brightnessctl -m | grep -P '\d+%' --only-matching | tr -d %)
# Show the brightness notification
dunstify -a "changeBrightness" -t "$timeout" -u low -i display-brightness -h string:x-dunst-stack-tag:$msgTag \
-h int:value:"$brightness" "Brightness: ${brightness}/100"

# Play the brightness changed sound
canberra-gtk-play -i audio-volume-change -d "changeBrightness"
