#!/usr/bin/env bash

cmd="$1"

shift 1
arguments="$@"

case $cmd in
    "volume")
        crock-change-volume $arguments
        ;;
    "brightness")
        crock-change-brightness $arguments
        ;;
    "mic-toggle")
        crock-mic-toggle $arguments
        ;;
    "gen-qr")
        crock-gen-qrcode $arguments
        ;;
    "power-menu")
        crock-rofi-power-menu $arguments
        ;;
    *)
        echo "Command not found"
        echo "Possible commands: volume, brightness, mic-toggle, gen-qr, power-menu"
esac
